### Get all

GET http://localhost:8080/api/employee

### Get existing single 

GET http://localhost:8080/api/employee/1

### Get non-existing single 

GET http://localhost:8080/api/employee/1134324342


### Add 
POST http://localhost:8080/api/employee 

{
    "Age": 40,
    "Namn": "Olena",
    "City": "Stockholm",
    "Age2": 201
  }

### Update existing
PUT http://localhost:8080/api/employee/1

  {
    "Age": 43,
    "Namn": "Man",
  }